version: 1.0.{build}

environment:
  secure_key:
    secure: 3n+Fp5U+pdW7mgyKwGA4EhdaXeuRaM8Tndwgx0mjvGjRz/e3EdVVh09GNlYoHbZg

install:
  - cmd: choco install nuget.commandline
  - ps: cd .\windows\chocolatey

build_script:
  - cmd: choco pack
  - cmd: choco install cmake
  - cmd: choco install biicode -source %cd%
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\ProgramData\chocolatey\lib\cmake.3.0.2\content\cmake-3.0.2-win32-x86\bin
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii;  

test_script:
  - cmd: bii --version
  - cmd: bii init test
  - cmd: cd test
  - cmd: bii open examples/zmq_cpp
  - cmd: bii cpp:configure -G "Visual Studio 12"
  - cmd: bii cpp:build

deploy_script:
  - ps: cd ..
  - ps: choco pack
  - cmd: set package = Get-ChildItem -Filter "*.nupkg"
  - cmd: nuget setApiKey %secure_key% -Source https://chocolatey.org/ 
  - cmd: nuget push %package% -ApiKey %secure_key% -Source https://chocolatey.org/ -NonInteractive


